spring:
  application:
    name: daily-clock-eureka-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  serviceUrl:
    defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
logging:
  file: /opt/tmp/eureka.log