server:
  port: 8000
security:
  user:
    name: kaixindaka
    password: kaixindaka@admin.com
spring:
  application:
    name: spring-cloud-admin-server
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8888}/eureka/